spring:
  application:
    name: dashboard
  datasource:
    url: jdbc:postgresql://postgresql:5432/mydatabase
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update