spring:
  application:
    name: dashboard
  datasource:
    url: jdbc:postgresql://postgresql:5432/mydatabase
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers:  kafka:9092
    consumer:
      group-id: dashboard-app
    topic:
      auto-create: true
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
logging:
  level:
    root: WARN